/**
 * Server-side universe lists.
 * Keep F&O / Nifty lists in sync with src/services/radar/universeCatalog.ts.
 * NSE / CASH cash book is loaded from src/data/nseEquity.json (same file the client uses).
 */
import { readFileSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';
export const NIFTY_50_SYMBOLS = [
  "ADANIENT",
  "ADANIPORTS",
  "APOLLOHOSP",
  "ASIANPAINT",
  "AXISBANK",
  "BAJAJFINSV",
  "BAJFINANCE",
  "BHARTIARTL",
  "BPCL",
  "BRITANNIA",
  "CIPLA",
  "COALINDIA",
  "DIVISLAB",
  "DRREDDY",
  "EICHERMOT",
  "GRASIM",
  "HCLTECH",
  "HDFCBANK",
  "HDFCLIFE",
  "HEROMOTOCO",
  "HINDALCO",
  "HINDUNILVR",
  "ICICIBANK",
  "INDUSINDBK",
  "INFY",
  "ITC",
  "JSWSTEEL",
  "KOTAKBANK",
  "LT",
  "M&M",
  "MARUTI",
  "NESTLEIND",
  "NTPC",
  "ONGC",
  "POWERGRID",
  "RELIANCE",
  "SBILIFE",
  "SBIN",
  "SUNPHARMA",
  "TATACONSUM",
  "TATAMOTORS",
  "TATASTEEL",
  "TCS",
  "TECHM",
  "TITAN",
  "ULTRACEMCO",
  "WIPRO",
  "BEL",
  "TRENT",
  "LICI"
];
export const FNO_EXTRA_UNDERLYINGS = [
  "360ONE",
  "ABB",
  "ABCAPITAL",
  "ADANIENSOL",
  "ADANIENT",
  "ADANIGREEN",
  "ADANIPORTS",
  "ADANIPOWER",
  "ALKEM",
  "AMBER",
  "AMBUJACEM",
  "ANGELONE",
  "APLAPOLLO",
  "APOLLOHOSP",
  "ASHOKLEY",
  "ASIANPAINT",
  "ASTRAL",
  "AUBANK",
  "AUROPHARMA",
  "AXISBANK",
  "BAJAJ-AUTO",
  "BAJAJFINSV",
  "BAJAJHLDNG",
  "BAJFINANCE",
  "BANDHANBNK",
  "BANKBARODA",
  "BANKINDIA",
  "BDL",
  "BEL",
  "BHARATFORG",
  "BHARTIARTL",
  "BHEL",
  "BIOCON",
  "BLUESTARCO",
  "BOSCHLTD",
  "BPCL",
  "BRITANNIA",
  "BSE",
  "CAMS",
  "CANBK",
  "CDSL",
  "CGPOWER",
  "CHOLAFIN",
  "CIPLA",
  "COALINDIA",
  "COCHINSHIP",
  "COFORGE",
  "COLPAL",
  "CONCOR",
  "CROMPTON",
  "CUMMINSIND",
  "DABUR",
  "DALBHARAT",
  "DELHIVERY",
  "DIVISLAB",
  "DIXON",
  "DLF",
  "DMART",
  "DRREDDY",
  "EICHERMOT",
  "ETERNAL",
  "FEDERALBNK",
  "FORCEMOT",
  "FORTIS",
  "GAIL",
  "GLENMARK",
  "GMRAIRPORT",
  "GODFRYPHLP",
  "GODREJCP",
  "GODREJPROP",
  "GRASIM",
  "GVT&D",
  "HAL",
  "HAVELLS",
  "HCLTECH",
  "HDFCAMC",
  "HDFCBANK",
  "HDFCLIFE",
  "HEROMOTOCO",
  "HINDALCO",
  "HINDPETRO",
  "HINDUNILVR",
  "HINDZINC",
  "HYUNDAI",
  "ICICIBANK",
  "ICICIGI",
  "ICICIPRULI",
  "IDEA",
  "IDFCFIRSTB",
  "IEX",
  "INDHOTEL",
  "INDIANB",
  "INDIGO",
  "INDUSINDBK",
  "INDUSTOWER",
  "INFY",
  "INOXWIND",
  "IOC",
  "IREDA",
  "IRFC",
  "ITC",
  "JINDALSTEL",
  "JIOFIN",
  "JSWENERGY",
  "JSWSTEEL",
  "JUBLFOOD",
  "KALYANKJIL",
  "KAYNES",
  "KEI",
  "KFINTECH",
  "KOTAKBANK",
  "KPITTECH",
  "LAURUSLABS",
  "LICHSGFIN",
  "LICI",
  "LODHA",
  "LT",
  "LTF",
  "LTM",
  "LUPIN",
  "M&M",
  "MANAPPURAM",
  "MANKIND",
  "MARICO",
  "MARUTI",
  "MAXHEALTH",
  "MAZDOCK",
  "MCX",
  "MFSL",
  "MOTHERSON",
  "MOTILALOFS",
  "MPHASIS",
  "MUTHOOTFIN",
  "NAM-INDIA",
  "NATIONALUM",
  "NAUKRI",
  "NBCC",
  "NESTLEIND",
  "NHPC",
  "NMDC",
  "NTPC",
  "NYKAA",
  "OBEROIRLTY",
  "OFSS",
  "OIL",
  "ONGC",
  "PAGEIND",
  "PATANJALI",
  "PAYTM",
  "PERSISTENT",
  "PETRONET",
  "PFC",
  "PGEL",
  "PHOENIXLTD",
  "PIDILITIND",
  "PIIND",
  "PNB",
  "PNBHOUSING",
  "POLICYBZR",
  "POLYCAB",
  "POWERGRID",
  "POWERINDIA",
  "PREMIERENE",
  "PRESTIGE",
  "RADICO",
  "RBLBANK",
  "RECLTD",
  "RELIANCE",
  "RVNL",
  "SAIL",
  "SBICARD",
  "SBILIFE",
  "SBIN",
  "SHREECEM",
  "SHRIRAMFIN",
  "SIEMENS",
  "SOLARINDS",
  "SONACOMS",
  "SRF",
  "SUNPHARMA",
  "SUPREMEIND",
  "SUZLON",
  "SWIGGY",
  "TATACONSUM",
  "TATAELXSI",
  "TATAPOWER",
  "TATASTEEL",
  "TCS",
  "TECHM",
  "TIINDIA",
  "TITAN",
  "TMPV",
  "TORNTPHARM",
  "TRENT",
  "TVSMOTOR",
  "ULTRACEMCO",
  "UNIONBANK",
  "UNITDSPR",
  "UNOMINDA",
  "UPL",
  "VBL",
  "VEDL",
  "VMM",
  "VOLTAS",
  "WAAREEENER",
  "WIPRO",
  "YESBANK",
  "ZYDUSLIFE"
];

export function getNifty50Universe() {
  return [...NIFTY_50_SYMBOLS];
}

export function getFnoUniverse() {
  return [...new Set(FNO_EXTRA_UNDERLYINGS)];
}

let nseCashCache = null;
export function getNseCashUniverse() {
  if (nseCashCache) return nseCashCache;
  try {
    const p = resolve(dirname(fileURLToPath(import.meta.url)), '../../src/data/nseEquity.json');
    const rows = JSON.parse(readFileSync(p, 'utf8'));
    nseCashCache = [
      ...new Set(
        (Array.isArray(rows) ? rows : []).map((r) => String(r?.s || '').toUpperCase()).filter(Boolean),
      ),
    ];
  } catch {
    nseCashCache = getNifty50Universe();
  }
  return nseCashCache;
}

export function resolveServerUniverse(universe) {
  const id = String(universe || 'F&O');
  if (id === 'NIFTY50' || id === 'NIFTY') return getNifty50Universe();
  if (id === 'CASH' || id === 'NSE') return getNseCashUniverse();
  if (id === 'BANKNIFTY') {
    return [
      'HDFCBANK',
      'ICICIBANK',
      'AXISBANK',
      'KOTAKBANK',
      'SBIN',
      'INDUSINDBK',
      'BANKBARODA',
      'FEDERALBNK',
      'IDFCFIRSTB',
      'PNB',
      'AUBANK',
      'BANDHANBNK',
    ];
  }
  return getFnoUniverse();
}
