/**
 * Server-side universe lists (inlined — no filesystem read at boot).
 * Keep in sync with src/services/radar/universeCatalog.ts
 */
export const NIFTY_50_SYMBOLS = [
  "ADANIENT",
  "ADANIPORTS",
  "APOLLOHOSP",
  "ASIANPAINT",
  "AXISBANK",
  "BAJAJFINSV",
  "BAJFINANCE",
  "BHARTIARTL",
  "BPCL",
  "BRITANNIA",
  "CIPLA",
  "COALINDIA",
  "DIVISLAB",
  "DRREDDY",
  "EICHERMOT",
  "GRASIM",
  "HCLTECH",
  "HDFCBANK",
  "HDFCLIFE",
  "HEROMOTOCO",
  "HINDALCO",
  "HINDUNILVR",
  "ICICIBANK",
  "INDUSINDBK",
  "INFY",
  "ITC",
  "JSWSTEEL",
  "KOTAKBANK",
  "LT",
  "M&M",
  "MARUTI",
  "NESTLEIND",
  "NTPC",
  "ONGC",
  "POWERGRID",
  "RELIANCE",
  "SBILIFE",
  "SBIN",
  "SUNPHARMA",
  "TATACONSUM",
  "TATAMOTORS",
  "TATASTEEL",
  "TCS",
  "TECHM",
  "TITAN",
  "ULTRACEMCO",
  "WIPRO",
  "BEL",
  "TRENT",
  "LICI"
];
export const FNO_EXTRA_UNDERLYINGS = [
  "ABB",
  "ABCAPITAL",
  "ABFRL",
  "ACC",
  "AARTIIND",
  "ALKEM",
  "AMBUJACEM",
  "ANGELONE",
  "ASHOKLEY",
  "ASTRAL",
  "ATUL",
  "AUBANK",
  "AUROPHARMA",
  "BALKRISIND",
  "BANDHANBNK",
  "BANKBARODA",
  "BATAINDIA",
  "BERGEPAINT",
  "BIOCON",
  "BHEL",
  "BOSCHLTD",
  "CANBK",
  "CANFINHOME",
  "CHAMBLFERT",
  "CHOLAFIN",
  "COLPAL",
  "CONCOR",
  "COROMANDEL",
  "CROMPTON",
  "CUMMINSIND",
  "DABUR",
  "DALBHARAT",
  "DEEPAKNTR",
  "DELHIVERY",
  "DIXON",
  "DLF",
  "DMART",
  "ESCORTS",
  "EXIDEIND",
  "FEDERALBNK",
  "GAIL",
  "GLENMARK",
  "GMRINFRA",
  "GNFC",
  "GODREJCP",
  "GODREJPROP",
  "GRANULES",
  "HAL",
  "HAVELLS",
  "HDFCAMC",
  "HINDPETRO",
  "HINDZINC",
  "IDFC",
  "IDFCFIRSTB",
  "IEX",
  "IGL",
  "INDIACEM",
  "INDIAMART",
  "INDIGO",
  "INDUSTOWER",
  "IOC",
  "IPCALAB",
  "IRCTC",
  "IRFC",
  "JINDALSTEL",
  "JIOFIN",
  "JKCEMENT",
  "JUBLFOOD",
  "KALYANKJIL",
  "KEI",
  "LALPATHLAB",
  "LAURUSLABS",
  "LICHSGFIN",
  "LODHA",
  "LTIM",
  "LUPIN",
  "MANAPPURAM",
  "MARICO",
  "MCX",
  "METROPOLIS",
  "MFSL",
  "MGL",
  "MOTHERSON",
  "MPHASIS",
  "MRF",
  "MUTHOOTFIN",
  "NAM-INDIA",
  "NAUKRI",
  "NAVINFLUOR",
  "NMDC",
  "OBEROIRLTY",
  "OFSS",
  "PAGEIND",
  "PATANJALI",
  "PEL",
  "PERSISTENT",
  "PETRONET",
  "PFC",
  "PIDILITIND",
  "PIIND",
  "PNB",
  "POLYCAB",
  "PVRINOX",
  "RAMCOCEM",
  "RBLBANK",
  "RECLTD",
  "SAIL",
  "SBICARD",
  "SHREECEM",
  "SIEMENS",
  "SRF",
  "SUPREMEIND",
  "SYNGENE",
  "TATACHEM",
  "TATACOMM",
  "TATAELXSI",
  "TATAPOWER",
  "TORNTPHARM",
  "TORNTPOWER",
  "TVSMOTOR",
  "UBL",
  "UPL",
  "VEDL",
  "VOLTAS",
  "YESBANK",
  "ZOMATO",
  "ZYDUSLIFE"
];

export function getNifty50Universe() {
  return [...NIFTY_50_SYMBOLS];
}

export function getFnoUniverse() {
  return [...new Set([...NIFTY_50_SYMBOLS, ...FNO_EXTRA_UNDERLYINGS])];
}

export function resolveServerUniverse(universe) {
  const id = String(universe || 'F&O');
  if (id === 'NIFTY50' || id === 'NIFTY') return getNifty50Universe();
  if (id === 'CASH') return getNifty50Universe();
  if (id === 'NSE' || id === 'NSE_EQ') {
    // Without live instrument master, honest DEMO snapshot = F&O underlyings + Nifty50 (not fake 6500).
    return getFnoUniverse();
  }
  if (id === 'BSE' || id === 'BSE_EQ') {
    return getFnoUniverse();
  }
  if (id === 'BANKNIFTY') {
    return [
      'HDFCBANK',
      'ICICIBANK',
      'AXISBANK',
      'KOTAKBANK',
      'SBIN',
      'INDUSINDBK',
      'BANKBARODA',
      'FEDERALBNK',
      'IDFCFIRSTB',
      'PNB',
      'AUBANK',
      'BANDHANBNK',
    ];
  }
  return getFnoUniverse();
}
